name: Approve PR via issue comment (fixed)

permissions:
  contents: write
  pull-requests: write

on:
  issue_comment:
    types: [created]

jobs:
  approve-pr:
    name: Approve and merge PR
    runs-on: ubuntu-latest
    if: >-
      contains(github.event.comment.body, '/approve-pr') &&
      (github.event.comment.author_association == 'OWNER' ||
       github.event.comment.author_association == 'MEMBER' ||
       github.event.comment.author_association == 'COLLABORATOR')

    steps:
      - name: Parse comment & merge PR
        uses: actions/github-script@v6
        with:
          script: |
            const body = context.payload.comment.body || '';
            const m = body.match(/\/approve-pr\s+#?(\d+)/i);
            if (!m) {
              core.setFailed('No PR number found in comment. Use "/approve-pr #123"');
              return;
            }
            const prNumber = parseInt(m[1], 10);
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            core.info(`Attempting to merge PR #${prNumber} in ${owner}/${repo}`);

            try {
              const pr = await github.pulls.get({ owner, repo, pull_number: prNumber });
              if (pr.data.merged) {
                core.info(`PR #${prNumber} is already merged.`);
                return;
              }
            } catch (err) {
              core.setFailed(`Failed to get PR #${prNumber}: ${err.message}`);
              return;
            }

            try {
              await github.pulls.merge({ owner, repo, pull_number: prNumber, merge_method: 'merge' });
              core.info(`PR #${prNumber} merged successfully.`);
            } catch (err) {
              core.setFailed(`Failed to merge PR #${prNumber}: ${err.message}`);
            }
