name: Approve PR via issue comment

permissions:
  contents: write
  pull-requests: write

on:
  issue_comment:
    types: [created]

jobs:
  approve-pr:
    runs-on: ubuntu-latest
    if: >
      contains(github.event.comment.body, '/approve-pr') &&
      (github.event.comment.author_association == 'OWNER' ||
       github.event.comment.author_association == 'MEMBER' ||
       github.event.comment.author_association == 'COLLABORATOR')
    steps:
      - name: Parse comment & merge PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACTIONS_PUSH_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const body = context.payload.comment.body || '';
            const m = body.match(/\/approve-pr\s+#?(\d+)/i);
            if (!m) {
              core.setFailed('No PR number found in comment. Use "/approve-pr #123"');
              return;
            }
            const prNumber = parseInt(m[1], 10);
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            try {
              const pr = await github.rest.pulls.get({ owner, repo, pull_number: prNumber });
              if (pr.data.merged) {
                core.info(`PR #${prNumber} already merged.`);
                return;
              }
            } catch (err) {
              core.setFailed(`Failed to get PR #${prNumber}: ${err.message}`);
              return;
            }
            try {
              await github.rest.pulls.merge({ owner, repo, pull_number: prNumber, merge_method: 'squash' });
              core.info(`PR #${prNumber} squashed and merged successfully.`);
            } catch (err) {
              core.setFailed(`Failed to squash-merge PR #${prNumber}: ${err.message}`);
            }
