name: Approve PR via issue comment

permissions:
  contents: write
  pull-requests: write

on:
  issue_comment:
    types: [created]

jobs:
  approve-pr:
    runs-on: ubuntu-latest
    if: >
      github.event.comment.body != null && (
        contains(github.event.comment.body, 'approve-pr') ||
        contains(github.event.comment.body, 'Approve-pr') ||
        contains(github.event.comment.body, 'approve-PR')
      ) &&
      (github.event.comment.author_association == 'OWNER' ||
       github.event.comment.author_association == 'MEMBER' ||
       github.event.comment.author_association == 'COLLABORATOR')
    steps:
      - name: Detect ACTIONS_PUSH_TOKEN
        id: detect_pat
        shell: bash
        env:
          ACTIONS_PUSH_TOKEN: ${{ secrets.ACTIONS_PUSH_TOKEN }}
        run: |
          if [ -n "${ACTIONS_PUSH_TOKEN}" ]; then
            echo "has_pat=true" >> $GITHUB_OUTPUT
          else
            echo "has_pat=false" >> $GITHUB_OUTPUT
          fi

      - name: Parse comment & merge PR (use ACTIONS_PUSH_TOKEN)
        if: ${{ steps.detect_pat.outputs.has_pat == 'true' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACTIONS_PUSH_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            const scriptPath = path.join(process.cwd(), '.github', 'scripts', 'approve-pr.js');
            if (!fs.existsSync(scriptPath)) {
              core.setFailed(`Shared script not found at ${scriptPath}`);
            } else {
              require(scriptPath);
              await globalThis.approvePR(github, context, core);
            }

      - name: Parse comment & merge PR (fallback to GITHUB_TOKEN)
        if: ${{ steps.detect_pat.outputs.has_pat == 'false' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            const scriptPath = path.join(process.cwd(), '.github', 'scripts', 'approve-pr.js');
            if (!fs.existsSync(scriptPath)) {
              core.setFailed(`Shared script not found at ${scriptPath}`);
            } else {
              require(scriptPath);
              await globalThis.approvePR(github, context, core);
            }
