name: Check MkDocs build on PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies (Poetry)
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Build MkDocs site
        run: |
          poetry run mkdocs build

      - name: Verify site built
        run: |
          if [ ! -d site ] || [ ! -f site/index.html ]; then
            echo "MkDocs build failed: site/index.html not found"; exit 1
          fi
