name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_PUSH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies (pip)
        run: |
          python -m pip install --upgrade pip
          python -m pip install "pandas>=2.3.3,<3.0.0" "openpyxl>=3.1.5,<4.0.0"
          # dev/test tooling aligned with pyproject.toml
          python -m pip install "pytest>=8.4.2,<9.0.0" "pytest-cov>=4.0.0,<5.0.0" "black>=25.9.0,<26.0.0" "isort>=5.10.1,<8.0.0" codecov

      - name: Run black (check)
        run: python -m black --check .

      - name: Run tests
        run: python -m pytest -q --cov=src --cov-report=xml

      - name: Upload coverage to Codecov
        if: ${{ env.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ env.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
