name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - --version 1.5.1
          # add poetry to PATH using the supported $GITHUB_PATH file
          echo "${HOME}/.local/bin" >> "$GITHUB_PATH"

      - name: Cache Poetry and pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies (export + pip install)
        run: |
          # avoid running `poetry install --with dev` directly in CI which may fail on some runners
          echo "POETRY_VIRTUALENVS_CREATE=false" >> "$GITHUB_ENV"
          poetry --version
          # ensure lockfile is available and up to date
          poetry lock --no-update || true
          # export runtime + dev requirements to a requirements.txt and install via pip
          poetry export -f requirements.txt --without-hashes --output requirements.txt --with dev || poetry export -f requirements.txt --without-hashes --output requirements.txt
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run black (check)
        run: |
          poetry run black --check .

      - name: Run tests
        run: |
          poetry run pytest -q --cov=src --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
