name: Dev PRs and sync to Main (fixed)

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch: # require manual trigger to create PR from dev -> main

jobs:
  test-and-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "pandas>=2.3.3,<3.0.0" "openpyxl>=3.1.5,<4.0.0"
          python -m pip install "pytest>=8.4.2,<9.0.0" "pytest-cov>=4.0.0,<5.0.0"

      - name: Run tests
        run: python -m pytest -q --maxfail=1

      - name: Create Pull Request to main (manual)
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ACTIONS_PUSH_TOKEN }}
          commit-message: "chore: sync dev -> main (manual)"
          title: "chore: sync dev -> main"
          body: "Manual PR created by CI workflow (triggered via workflow_dispatch)."
          base: main
          branch: dev
