name: Build and deploy MkDocs to docs branch

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies (Poetry)
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Build MkDocs site
        run: |
          poetry run mkdocs build

      - name: Deploy to GitHub Pages (push to docs branch)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: docs
          keep_files: false
          force_orphan: true
