name: Pre-commit autoupdate

on:
  schedule:
    - cron: '0 0 * * 0' # weekly
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit
      - name: Run pre-commit autoupdate
        run: |
          pre-commit autoupdate
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .pre-commit-config.yaml
          git commit -m "chore(ci): update pre-commit hooks" || echo 'no changes'
          git push
