name: Push -> test and create PR

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - "feature/**"
      - "test/**"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install project runtime dependencies
          python -m pip install "pandas>=2.3.3,<3.0.0" "openpyxl>=3.1.5,<4.0.0"
          # install test tooling
          python -m pip install "pytest>=8.4.2,<9.0.0"
      - name: Run tests
        run: python -m pytest -q --maxfail=1

  create_pr:
    name: Create or update PR to dev
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create or update PR to dev
        id: create
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const branch = context.ref.replace('refs/heads/','');
            const title = `ci: sync(${branch}) -> dev [auto]`;
            const body = `This PR was automatically created/updated by CI after tests passed on branch ${branch}.`;
            const head = branch;
            const resp = await github.rest.pulls.list({ owner, repo, state: 'open', head, per_page: 100 });
            const prs = resp.data || [];
            if (!prs || prs.length === 0) {
              const createResp = await github.rest.pulls.create({ owner, repo, title, head: branch, base: 'dev', body });
              core.setOutput('pr_number', createResp.data.number.toString());
              core.setOutput('pr_html_url', createResp.data.html_url);
            } else {
              const pr = prs[0];
              await github.rest.pulls.update({ owner, repo, pull_number: pr.number, title, body });
              core.setOutput('pr_number', pr.number.toString());
              core.setOutput('pr_html_url', pr.html_url);
            }
