name: Update Codecov badge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0' # semanal aos domingos 03:00 UTC (opcional)

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Codecov badge SVG
        id: fetch_badge
        run: |
          REPO="ulissesbomjardim/estrutura_workshop"
          URL="https://codecov.io/gh/${REPO}/branch/main/graph/badge.svg"
          echo "Fetching ${URL}"
          curl -fsSL "$URL" -o badge.svg || true
          if [ -f badge.svg ]; then
            # check if badge contains a percent (simple heuristic)
            if grep -q "[0-9]\+%" badge.svg; then
              echo "badge_found=true" >> $GITHUB_OUTPUT
            else
              echo "badge_found=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "badge_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Update README with real badge and push
        if: steps.fetch_badge.outputs.badge_found == 'true'
        run: |
          # copy badge to repo and build markdown linking to Codecov
          cat badge.svg > codecov-badge.svg
          BADGE_MD="[![Codecov](./codecov-badge.svg)](https://codecov.io/gh/${GITHUB_REPOSITORY})"

          # If placeholder exists (shields.io badge), replace it; otherwise insert at top
          if grep -q "shields.io/badge/coverage-unknown" README.md; then
            # replace the first occurrence using perl (multiline safe)
            perl -0777 -pe "s/\[!\[Codecov\]\([^\)]*coverage-unknown[^\)]*\)\]\([^\)]*\)/${BADGE_MD}/s" -i README.md
          else
            # prepend badge using a temp file to avoid YAML quoting issues
            (echo "${BADGE_MD}"; echo; cat README.md) > README.new && mv README.new README.md
          fi

          # commit and push
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add codecov-badge.svg README.md
          git commit -m "chore(ci): update Codecov badge" || echo 'no changes'
          git push
